default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: rails_watch_list_production
  username: rails_watch_list
  password: <%= ENV["RAILS_WATCH_LIST_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: rails-watch-list_development

test:
  <<: *default
  database: rails-watch-list_test
